# Generated by Django 6.0.6 on 2026-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_conferenceroom_conferencebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencebooking',
            name='selected_packages',
            field=models.TextField(blank=True, help_text='JSON list of selected packages'),
        ),
    ]
